"""show_transform.py -- the per-WORD Unicode -> legacy-key table, for review.

    py scripts/show_transform.py <lrc> [--font abhinav] [--layout Preeti]
                                 [--only-wrong] [--all]

A font's sweep.json CLASS decides how it is encoded, and that changes everything
about what to check (gotcha 34):

  PREETI   the font uses npttf2utf's built-in Preeti mapping, so a plain
           --legacy-font is safe -- there is no generated map.json to be wrong.
           Abhinav is in this class.
  GENERATED the font's keys came from a sweep, and the sweep DROPPED slots it
           could not classify, so every divergent slot can render the wrong
           glyph. AMS Cinema is in this class.

Either way the next question is separate, and it is gotcha 23's whole point: can
this song's WORDS be written in these keys at all?

So this runs the same encoder the render uses (scripts/lrc_legacy.py's
convert_line), decodes the keys back, and prints both so every word can be
compared by eye before anyone spends six minutes rendering.

A word is safe if it round-trips. "Lost" names the characters with no key, since
those reach Chromium unmapped and get drawn in a different font -- and a word
that loses its VIRAMA is not a spelling slip, it is a split character: the
virama is what fuses a conjunct.

WARNING, learned the hard way: do NOT edit this file (or any file with
non-ASCII) by round-tripping it through PowerShell `Get-Content`/`Set-Content`.
The default encoding double-encodes UTF-8 and silently turns every Devanagari
literal into mojibake. That corrupted the ऊ fix below and made three correct
words look broken. Use a real editor, or the Edit tool.
"""
import argparse
import os
import re
import sys
import unicodedata
from collections import Counter, OrderedDict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.stdout.reconfigure(encoding="utf-8")

from lrc_legacy import convert_line
from layout_encoder import _decode

STAMP = re.compile(r"\[(\d{1,3}):([0-5]?\d(?:[.:]\d{1,3})?)\]")
META = re.compile(r"^\[(ti|ar|al|au|by|re|ve|length|offset|ti-font|ti-fontfile):", re.I)

NAMES = {
    0x094D: "virama (halant) - fuses a conjunct",
    0x0901: "candrabindu - the crescent above a letter",
    0x0902: "anusvara (bindu)",
    0x0900: "khanda",
    0x0909: "vowel letter U",
    0x090A: "vowel letter UU",
    0x0964: "danda",
    0x0965: "double danda",
}


def describe(ch):
    try:
        n = unicodedata.name(ch)
    except ValueError:
        n = "?"
    return NAMES.get(ord(ch), n)


def read_words(path):
    """Every distinct word, with the cue it first appears in."""
    seen = OrderedDict()
    cue = 0
    with open(path, encoding="utf-8-sig") as f:
        for raw in f:
            raw = raw.strip()
            if not raw or META.match(raw):
                continue
            text = STAMP.sub("", raw).strip()
            if not text:
                continue
            cue += len(STAMP.findall(raw))
            for w in text.split():
                core = w.strip(".,!?;:।॥…-")
                if core and core not in seen:
                    seen[core] = cue
    return seen


def decode_back(keys, layout):
    """Decode keys to Unicode the way convert_line verifies them.

    These two replacements are the Preeti ambiguities: the map has no distinct
    key for the long forms, so the encoder emits u-matra + u and the reader has
    to fold it back. They are part of the contract, not a fudge -- and they
    must stay byte-exact, or correct words start looking broken.
    """
    back = _decode(keys, layout)
    for wrong, right in (("उू", "ऊ"), ("इी", "ई")):
        back = back.replace(wrong, right)
    return back


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("lrc")
    ap.add_argument("--font", default="abhinav")
    ap.add_argument("--layout", default="Preeti",
                    help="Preeti = npttf2utf built-in (a PREETI-class font). "
                         "A generated slug needs its layout file, which this "
                         "script does not load -- use check_song.py for those.")
    ap.add_argument("--only-wrong", action="store_true")
    ap.add_argument("--all", action="store_true")
    a = ap.parse_args()

    words = read_words(a.lrc)
    print("=" * 96)
    print("  %s -- %d distinct words -- layout: %s" % (
        os.path.basename(a.lrc), len(words), a.layout))
    print("=" * 96)

    bad, exact, lost = [], [], Counter()
    for w, cue in words.items():
        keys = convert_line(w, a.layout)
        back = decode_back(keys, a.layout)
        if back == w:
            exact.append((w, keys, cue))
            continue
        missing = [c for c in dict.fromkeys(w) if c not in back]
        for c in missing:
            lost[c] += 1
        bad.append((w, keys, back, cue, missing))

    if not a.only_wrong or a.all:
        print("\n  ROUND-TRIPS EXACTLY  (%d words)\n" % len(exact))
        print("    %-24s %-22s %s" % ("word", "becomes (keys)", "cue"))
        print("    " + "-" * 58)
        for w, keys, cue in exact:
            print("    %-24s %-22s %d" % (w, keys, cue))

    print("\n  DOES NOT ROUND-TRIP  (%d words)" % len(bad))
    if bad:
        print()
        print("    %-20s %-20s %-20s %s" % ("original", "becomes", "decodes as", "cue"))
        print("    " + "-" * 74)
        for w, keys, back, cue, missing in bad:
            print("    %-20s %-20s %-20s %d  <-- CHANGED" % (w, keys, back, cue))
            for c in missing:
                print("        lost %r  U+%04X  %s" % (c, ord(c), describe(c)))

    print("\n" + "=" * 96)
    if bad:
        print("  VERDICT: %s CANNOT write every word of this song." % a.font.upper())
        print("  %d of %d distinct words change." % (len(bad), len(words)))
        for c, n in lost.most_common():
            print("    %r  U+%04X  x%-3d  %s" % (c, ord(c), n, describe(c)))
    else:
        print("  VERDICT: all %d words round-trip in the %s layout." % (len(words), a.layout))
        print("  The ENCODER and DECODER agree. That is still not proof the FONT")
        print("  draws the right glyph -- check with check_font_cmap.py for")
        print("  coverage, and your eyes on a still for identity.")
    print("=" * 96)
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
